name: Hello World

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Say Hello
    steps:
      - name: Hello World
        uses: jimhoc94/action01@main
        with:
          owner: ${{ github.repository_owner }}
