name: Repo sync

jobs:
  Sync:
    runs-on: ubuntu-latest
    name: Repo Sync
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get File
        uses: jimhoc94/action01@develop
        with:
          owner: ${{ github.repository_owner }}
      - name: Commit
        run: |
          git config --global user.name 'jimhoc94'
          git config --global user.email 'jimhoc94@users.noreply.github.com'
          git add -A
          git commit -am "Automated report"
          git push
